// src/pipeline/pipelineGenerator.js
// ─────────────────────────────────────────────────────────────
// Day 6 — CI/CD Pipeline Generator.
//
// Takes the deploymentConfig produced by Day 5 (gcpPlanner.js) and:
//
//   1. generatePipelineYml(deploymentConfig)
//      Produces a complete .gitlab-ci.yml string.
//      Pure function — no network calls, no side effects.
//      Generates different jobs based on what infrastructure
//      Day 5 detected (Cloud Run, Cloud SQL, Memorystore, etc.)
//
//   2. commitAndDeploy(projectId, deploymentConfig, onProgress)
//      Commits .gitlab-ci.yml to the repo, finds the resulting pipeline,
//      and polls it every 5 seconds until it finishes or fails.
//      Pushes live status to the frontend via onProgress.
//
//   3. getPipelineStatus(projectId, pipelineId)
//      On-demand status refresh — called by the frontend whenever it
//      wants the latest job statuses without waiting for a full poll cycle.
//
// ── GitLab CI Variables the user must set ────────────────────
// Before the generated pipeline can actually run, the user needs to go to
// their GitLab repo → Settings → CI/CD → Variables and add:
//
//   GCP_PROJECT_ID              — their GCP project ID
//   GCP_SERVICE_ACCOUNT_KEY     — JSON key for a GCP service account
//                                 with the following IAM roles:
//                                   roles/run.admin
//                                   roles/artifactregistry.writer
//                                   roles/iam.serviceAccountUser
//                                   roles/cloudsql.client (if using Cloud SQL)
//
// See API_KEYS_SETUP.md for how to create the service account and download the key.
// ─────────────────────────────────────────────────────────────

const {
  getDefaultBranch,
  commitFile,
  getProjectPipelines,
  getPipelineJobs,
} = require('../api/gitlabClient');

const POLL_INTERVAL_MS  = 5000;       // Poll every 5 seconds
const POLL_TIMEOUT_MINS = 30;         // Give up after 30 minutes
const POLL_MAX_ATTEMPTS = (POLL_TIMEOUT_MINS * 60 * 1000) / POLL_INTERVAL_MS;

// Pipeline statuses from the GitLab API
const RUNNING_STATUSES  = new Set(['created', 'waiting_for_resource', 'preparing', 'pending', 'running', 'scheduled']);
const TERMINAL_STATUSES = new Set(['success', 'failed', 'canceled', 'skipped']);

// ════════════════════════════════════════════════════════════
// 1. YAML GENERATOR
// ════════════════════════════════════════════════════════════

/**
 * generatePipelineYml
 * Builds a complete .gitlab-ci.yml string from the deploymentConfig.
 *
 * Pipeline stages:
 *   build  → Docker build + push to Artifact Registry
 *   deploy → gcloud run deploy (+ optional Cloud SQL / Memorystore checks)
 *   verify → curl the deployed /health endpoint
 *
 * @param {Object} deploymentConfig - From gcpPlanner.buildDeploymentConfig()
 * @param {string} branch           - The repo's default branch name
 * @returns {string} Complete .gitlab-ci.yml content
 */
function generatePipelineYml(deploymentConfig, branch = 'main') {
  const { region, cloudRun, cloudSQL, memorystore, artifactRegistry } = deploymentConfig;

  // Artifact Registry image path:
  // LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/SERVICE:SHA
  const registryHost = `${artifactRegistry.location}-docker.pkg.dev`;
  const imageBase    = `${registryHost}/$GCP_PROJECT_ID/${artifactRegistry.repository}`;
  const imageFull    = `${imageBase}/${cloudRun.serviceName}:$CI_COMMIT_SHA`;

  // gcloud --set-env-vars flag:
  // Plain vars are inlined. Secret vars reference same-named CI variables.
  const envVarFlag   = buildEnvVarFlag(cloudRun.envVars || []);

  // Cloud SQL connection flag (blank string if no DB)
  const sqlFlag = cloudSQL
    ? `--add-cloudsql-instances=$GCP_PROJECT_ID:${region}:${cloudSQL.instanceName} \\`
    : '';

  // Optional extra jobs for Cloud SQL + Memorystore verification
  const cloudSqlJob     = cloudSQL      ? generateCloudSqlVerifyJob(region, cloudSQL,     branch) : '';
  const memorystoreJob  = memorystore   ? generateMemorystoreVerifyJob(region, memorystore, branch) : '';

  // Needs clause — deploy-cloud-run waits for these jobs before starting
  const deployNeeds = ['build-image'];
  if (cloudSQL)    deployNeeds.push('verify-cloud-sql');
  if (memorystore) deployNeeds.push('verify-memorystore');

  const deployNeedsYml = deployNeeds
    .map(j => `    - job: ${j}${j === 'build-image' ? '\n      artifacts: true' : ''}`)
    .join('\n');

  return `# .gitlab-ci.yml
# Generated by CloudMapper on ${new Date().toISOString().split('T')[0]}
# Service : ${cloudRun.serviceName}
# Region  : ${region}
# Registry: ${registryHost}
#
# ─── REQUIRED: Add these variables in GitLab → Settings → CI/CD → Variables ───
#
#   GCP_PROJECT_ID          — your GCP project ID  (e.g. my-project-123456)
#   GCP_SERVICE_ACCOUNT_KEY — JSON key for a GCP service account with roles:
#                               roles/run.admin
#                               roles/artifactregistry.writer
#                               roles/iam.serviceAccountUser${cloudSQL ? '\n#                               roles/cloudsql.client' : ''}
#
# How to create the service account — see API_KEYS_SETUP.md in this repo.
# ────────────────────────────────────────────────────────────────────────────────

stages:
  - build
  - deploy
  - verify

variables:
  # Resolved at job runtime — do not change these
  IMAGE_BASE: "${imageBase}"
  IMAGE_TAG:  "$CI_COMMIT_SHA"
  SERVICE:    "${cloudRun.serviceName}"
  REGION:     "${region}"

# ── Shared GCP authentication ─────────────────────────────────────────────────
# Runs before every job that needs gcloud or Docker auth.
# GCP_SERVICE_ACCOUNT_KEY is a masked CI variable containing the JSON key.
.gcp_auth: &gcp_auth
  before_script:
    - echo "$GCP_SERVICE_ACCOUNT_KEY" > /tmp/gcp-key.json
    - gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud auth configure-docker ${registryHost} --quiet

# ══════════════════════════════════════════════════════════════════════════════
# STAGE 1 — BUILD
# Builds the Docker image and pushes it to Artifact Registry.
# Tagged with both the commit SHA (for traceability) and 'latest'.
# ══════════════════════════════════════════════════════════════════════════════

build-image:
  stage: build
  image: google/cloud-sdk:alpine
  <<: *gcp_auth
  script:
    - echo "Building image for commit $CI_COMMIT_SHORT_SHA on branch $CI_COMMIT_REF_NAME"
    - docker build
        --tag "$IMAGE_BASE/${cloudRun.serviceName}:$CI_COMMIT_SHA"
        --tag "$IMAGE_BASE/${cloudRun.serviceName}:latest"
        --label "vcs.revision=$CI_COMMIT_SHA"
        --label "vcs.branch=$CI_COMMIT_REF_NAME"
        --label "built-by=cloudmapper"
        .
    - echo "Pushing image..."
    - docker push "$IMAGE_BASE/${cloudRun.serviceName}:$CI_COMMIT_SHA"
    - docker push "$IMAGE_BASE/${cloudRun.serviceName}:latest"
    - echo "IMAGE_FULL=$IMAGE_BASE/${cloudRun.serviceName}:$CI_COMMIT_SHA" > build.env
  artifacts:
    reports:
      dotenv: build.env
    expire_in: 1 hour
  only:
    - ${branch}
    - tags
${cloudSqlJob}${memorystoreJob}
# ══════════════════════════════════════════════════════════════════════════════
# STAGE 2 — DEPLOY
# Deploys the image to Cloud Run using the gcloud CLI.
# Waits for the build (and any infra checks) to pass first.
# ══════════════════════════════════════════════════════════════════════════════

deploy-cloud-run:
  stage: deploy
  image: google/cloud-sdk:alpine
  <<: *gcp_auth
  needs:
${deployNeedsYml}
  script:
    - echo "Deploying $SERVICE to Cloud Run ($REGION)..."
    - >
      gcloud run deploy $SERVICE
      --image="$IMAGE_FULL"
      --platform=managed
      --region=$REGION
      --cpu=${cloudRun.cpu || '2'}
      --memory=${cloudRun.memory || '1Gi'}
      --concurrency=${cloudRun.concurrency || 80}
      --min-instances=${cloudRun.minInstances ?? 1}
      --max-instances=${cloudRun.maxInstances || 20}
      ${sqlFlag}
      --set-env-vars="${envVarFlag}"
      --allow-unauthenticated
      --quiet
    - >
      SERVICE_URL=$(gcloud run services describe $SERVICE
      --platform=managed --region=$REGION
      --format='value(status.url)')
    - echo "SERVICE_URL=$SERVICE_URL" >> deploy.env
    - echo "Deployed to $SERVICE_URL"
  artifacts:
    reports:
      dotenv: deploy.env
  environment:
    name: production
    url: $SERVICE_URL
  only:
    - ${branch}
    - tags

# ══════════════════════════════════════════════════════════════════════════════
# STAGE 3 — VERIFY
# Hits the /health endpoint to confirm the service is live and responding.
# Fails the pipeline if the health check returns anything other than HTTP 200.
# ══════════════════════════════════════════════════════════════════════════════

verify-health:
  stage: verify
  image: alpine:latest
  needs:
    - job: deploy-cloud-run
      artifacts: true
  script:
    - apk add --no-cache curl --quiet
    - echo "Waiting 15s for Cloud Run to warm up..."
    - sleep 15
    - echo "Checking $SERVICE_URL/health ..."
    - |
      HTTP_STATUS=$(curl --silent --output /dev/null --write-out "%{http_code}" --max-time 10 "$SERVICE_URL/health")
      echo "Response: HTTP $HTTP_STATUS"
      if [ "$HTTP_STATUS" != "200" ]; then
        echo "FAIL: Expected 200, got $HTTP_STATUS"
        exit 1
      fi
      echo "PASS: Service is healthy"
  only:
    - ${branch}
    - tags
`;
}

// ── YAML sub-generators ───────────────────────────────────────

/**
 * buildEnvVarFlag
 * Converts the envVars list into a comma-separated string for
 * gcloud's --set-env-vars flag.
 *
 * Secret vars become $VAR_NAME (read from GitLab CI variables at runtime).
 * Plain vars are inlined as KEY=VALUE.
 */
function buildEnvVarFlag(envVars) {
  return envVars
    .map(v => v.secret ? `${v.name}=$${v.name}` : `${v.name}=${v.value}`)
    .join(',');
}

/**
 * generateCloudSqlVerifyJob
 * Checks the Cloud SQL instance exists and is RUNNABLE before deploying.
 * We verify rather than create — instances take several minutes to create
 * and should be provisioned once, not on every commit.
 */
function generateCloudSqlVerifyJob(region, cloudSQL, branch) {
  return `
# ──────────────────────────────────────────────────────────────
# Verifies the Cloud SQL instance exists before deploying.
# If it doesn't exist: create it in the GCP Console, then re-run this pipeline.
# ──────────────────────────────────────────────────────────────
verify-cloud-sql:
  stage: deploy
  image: google/cloud-sdk:alpine
  <<: *gcp_auth
  needs: []
  script:
    - echo "Checking Cloud SQL instance '${cloudSQL.instanceName}'..."
    - |
      STATUS=$(gcloud sql instances describe ${cloudSQL.instanceName} \\
        --project=$GCP_PROJECT_ID \\
        --format='value(state)' 2>/dev/null || echo "NOT_FOUND")
      if [ "$STATUS" = "NOT_FOUND" ]; then
        echo "ERROR: Cloud SQL instance '${cloudSQL.instanceName}' not found."
        echo "Create it in the GCP Console (Cloud SQL → Create Instance)."
        exit 1
      fi
      if [ "$STATUS" != "RUNNABLE" ]; then
        echo "ERROR: Cloud SQL instance is not RUNNABLE (state=$STATUS)"
        exit 1
      fi
      echo "Cloud SQL OK (state=$STATUS)"
  only:
    - ${branch}
    - tags

`;
}

/**
 * generateMemorystoreVerifyJob
 * Same pattern — verifies Memorystore Redis instance is READY.
 */
function generateMemorystoreVerifyJob(region, memorystore, branch) {
  return `
# ──────────────────────────────────────────────────────────────
# Verifies the Memorystore Redis instance exists before deploying.
# ──────────────────────────────────────────────────────────────
verify-memorystore:
  stage: deploy
  image: google/cloud-sdk:alpine
  <<: *gcp_auth
  needs: []
  script:
    - echo "Checking Memorystore instance '${memorystore.instanceName}'..."
    - |
      STATE=$(gcloud redis instances describe ${memorystore.instanceName} \\
        --region=${region} \\
        --project=$GCP_PROJECT_ID \\
        --format='value(state)' 2>/dev/null || echo "NOT_FOUND")
      if [ "$STATE" = "NOT_FOUND" ]; then
        echo "ERROR: Memorystore instance '${memorystore.instanceName}' not found."
        echo "Create it in the GCP Console (Memorystore → Create Instance)."
        exit 1
      fi
      if [ "$STATE" != "READY" ]; then
        echo "ERROR: Memorystore instance is not READY (state=$STATE)"
        exit 1
      fi
      echo "Memorystore OK (state=$STATE)"
  only:
    - ${branch}
    - tags

`;
}

// ════════════════════════════════════════════════════════════
// 2. COMMIT AND DEPLOY
// ════════════════════════════════════════════════════════════

/**
 * commitAndDeploy
 * Orchestrates the full Day 6 flow:
 *   A) Resolves the repo's default branch
 *   B) Generates .gitlab-ci.yml
 *   C) Commits it to the repo
 *   D) Waits for GitLab to create the pipeline
 *   E) Polls until the pipeline reaches a terminal state
 *
 * @param {number}   projectId        - GitLab project ID
 * @param {Object}   deploymentConfig - From gcpPlanner.buildDeploymentConfig()
 * @param {Function} onProgress       - Called with progress objects:
 *                                      { message, stage, pipelineId?, status?, jobs? }
 *
 * @returns {Object} {
 *   commitSha:   string,
 *   pipelineId:  number | null,
 *   pipelineUrl: string | null,
 *   finalStatus: string,
 *   jobs:        Object[],
 * }
 */
async function commitAndDeploy(projectId, deploymentConfig, onProgress = () => {}) {

  // ── A: Resolve default branch ─────────────────────────────
  onProgress({ message: 'Resolving default branch...', stage: 'preparing' });
  const branch = await getDefaultBranch(projectId);

  // ── B: Generate YAML ──────────────────────────────────────
  onProgress({ message: 'Generating .gitlab-ci.yml...', stage: 'generating' });
  const yml = generatePipelineYml(deploymentConfig, branch);
  onProgress({ message: `Pipeline YAML ready (${yml.split('\n').length} lines)`, stage: 'generating' });

  // ── C: Commit the file ────────────────────────────────────
  onProgress({ message: `Committing .gitlab-ci.yml to '${branch}'...`, stage: 'committing' });
  const commit = await commitFile(
    projectId,
    '.gitlab-ci.yml',
    yml,
    `chore(ci): deploy ${deploymentConfig.cloudRun?.serviceName || 'service'} to Cloud Run via CloudMapper`,
    branch
  );
  const commitSha = commit.id || commit.short_id;
  onProgress({ message: `Committed ${commitSha?.substring(0, 8)}`, stage: 'committing', commitSha });

  // ── D: Wait for pipeline to appear ───────────────────────
  onProgress({ message: 'Waiting for GitLab to trigger the pipeline...', stage: 'waiting' });
  const pipeline = await waitForPipeline(projectId, commitSha, onProgress);

  if (!pipeline) {
    return {
      commitSha,
      pipelineId:  null,
      pipelineUrl: null,
      finalStatus: 'not_triggered',
      jobs:        [],
      message:     'Pipeline was not triggered within 60 seconds. Make sure CI/CD is enabled for this repo.',
    };
  }

  onProgress({
    message:    `Pipeline #${pipeline.id} triggered`,
    stage:      'running',
    pipelineId: pipeline.id,
    status:     pipeline.status,
  });

  // ── E: Poll to completion ─────────────────────────────────
  const finalState = await pollUntilDone(projectId, pipeline.id, onProgress);

  return {
    commitSha,
    pipelineId:  pipeline.id,
    pipelineUrl: pipeline.web_url,
    finalStatus: finalState.status,
    jobs:        finalState.jobs,
  };
}

// ════════════════════════════════════════════════════════════
// 3. ON-DEMAND STATUS
// ════════════════════════════════════════════════════════════

/**
 * getPipelineStatus
 * Fetches the current state of a pipeline and its jobs.
 * Used by the frontend to refresh the Deployment Progress screen.
 *
 * @param {number} projectId  - GitLab project ID
 * @param {number} pipelineId - Pipeline ID
 * @returns {Object} Normalised pipeline state (see formatState)
 */
async function getPipelineStatus(projectId, pipelineId) {
  const [recentPipelines, jobs] = await Promise.all([
    getProjectPipelines(projectId, 20),
    getPipelineJobs(projectId, pipelineId),
  ]);

  const pipeline = recentPipelines.find(p => p.id === pipelineId)
    || { id: pipelineId, status: 'unknown' };

  return formatState(pipeline, jobs);
}

// ════════════════════════════════════════════════════════════
// PRIVATE HELPERS
// ════════════════════════════════════════════════════════════

/**
 * waitForPipeline
 * Polls the pipelines list looking for one whose SHA matches our commit.
 * GitLab takes a few seconds after a push to create the pipeline.
 * Tries for up to 60 seconds before returning null.
 */
async function waitForPipeline(projectId, commitSha, onProgress) {
  const maxAttempts = 12;

  for (let i = 0; i < maxAttempts; i++) {
    await sleep(POLL_INTERVAL_MS);
    const pipelines = await getProjectPipelines(projectId, 10);
    const match     = pipelines.find(p =>
      p.sha === commitSha || p.sha?.startsWith(commitSha) || commitSha?.startsWith(p.sha)
    );
    if (match) return match;
    onProgress({ message: `Waiting for pipeline... (${i + 1}/${maxAttempts})`, stage: 'waiting' });
  }
  return null;
}

/**
 * pollUntilDone
 * Polls a pipeline every POLL_INTERVAL_MS until it reaches a terminal status.
 */
async function pollUntilDone(projectId, pipelineId, onProgress) {
  for (let attempt = 0; attempt < POLL_MAX_ATTEMPTS; attempt++) {
    await sleep(POLL_INTERVAL_MS);

    const [recentPipelines, jobs] = await Promise.all([
      getProjectPipelines(projectId, 20),
      getPipelineJobs(projectId, pipelineId),
    ]);

    const pipeline = recentPipelines.find(p => p.id === pipelineId);
    const status   = pipeline?.status || 'unknown';
    const state    = formatState(pipeline || { id: pipelineId, status }, jobs);

    // Summarise job statuses for the progress message
    const jobSummary = state.jobs
      .map(j => `${j.name}: ${j.status}`)
      .join(' · ');

    onProgress({
      message:    `#${pipelineId} ${status} · ${jobSummary}`,
      stage:      'running',
      pipelineId,
      status,
      jobs:       state.jobs,
      isRunning:  state.isRunning,
      isComplete: state.isComplete,
    });

    if (TERMINAL_STATUSES.has(status)) {
      const icon = status === 'success' ? '✅' : '❌';
      onProgress({
        message:    `${icon} Pipeline ${status}`,
        stage:      'complete',
        pipelineId,
        status,
        jobs:       state.jobs,
        isRunning:  false,
        isComplete: true,
      });
      return state;
    }
  }

  return { status: 'timeout', jobs: [] };
}

/**
 * formatState
 * Normalises a raw GitLab pipeline + jobs array into a clean shape
 * for the frontend to consume.
 */
function formatState(pipeline, jobs = []) {
  const status = pipeline?.status || 'unknown';
  return {
    pipelineId:  pipeline?.id,
    status,
    webUrl:      pipeline?.web_url || null,
    isRunning:   RUNNING_STATUSES.has(status),
    isComplete:  TERMINAL_STATUSES.has(status),
    jobs: jobs.map(j => ({
      id:          j.id,
      name:        j.name,
      stage:       j.stage,
      status:      j.status,
      duration:    j.duration    || null,  // seconds, null if not yet finished
      startedAt:   j.started_at  || null,
      webUrl:      j.web_url     || null,
      allowFailure: j.allow_failure || false,
    })),
  };
}

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

module.exports = { generatePipelineYml, commitAndDeploy, getPipelineStatus };
