// src/agent/pipelineGenerator.js
// Generates a .gitlab-ci.yml string from scan result and GCP plan.
// Stages: build → test → deploy.

/**
 * generatePipelineYaml
 *
 * @param {Object} scanResult - From repoScanner.scanRepository() (or one service from services[])
 * @param {Object} gcpPlan    - From gcpPlanner.generateGcpPlan()
 * @returns {string} Contents for .gitlab-ci.yml (build → test → deploy)
 */
function generatePipelineYaml(scanResult, gcpPlan) {
  const stages = ['build', 'test', 'deploy'];
  const jobs = [];

  const summary = scanResult?.summary?.byType || {};
  const languages = summary.languages || [];
  const hasNode = languages.some(l => /node|javascript|typescript/i.test(l));
  const hasPython = languages.some(l => /python/i.test(l));
  const hasDocker = (scanResult?.infrastructure || []).some(i => /docker/i.test(i.name || ''));
  const deploymentConfig = gcpPlan?.deploymentConfig || {};
  const hasCloudRun = Boolean(deploymentConfig.cloudRun);
  const serviceName = deploymentConfig.cloudRun?.serviceName || 'app';
  const image = deploymentConfig.cloudRun?.image || deploymentConfig.artifactRegistry?.repository;

  // ── Build job(s) ─────────────────────────────────────────────
  if (hasNode) {
    jobs.push(buildJobNode(scanResult));
  }
  if (hasPython && !hasNode) {
    jobs.push(buildJobPython(scanResult));
  }
  if (!hasNode && !hasPython) {
    jobs.push(buildJobGeneric());
  }

  // ── Test job(s) ──────────────────────────────────────────────
  if (hasNode) {
    jobs.push(testJobNode(scanResult));
  }
  if (hasPython && !hasNode) {
    jobs.push(testJobPython(scanResult));
  }
  if (!hasNode && !hasPython) {
    jobs.push(testJobGeneric());
  }

  // ── Deploy job (when GCP plan includes Cloud Run) ────────────
  if (hasCloudRun) {
    jobs.push(deployJobCloudRun(scanResult, gcpPlan, deploymentConfig));
  } else {
    jobs.push(deployJobPlaceholder());
  }

  return [
    '# Generated by FlowForge pipeline generator',
    '# Stages: build → test → deploy',
    '',
    'stages:',
    stages.map(s => `  - ${s}`).join('\n'),
    '',
    jobs.join('\n\n'),
    '',
  ].join('\n');
}

function buildJobNode(scanResult) {
  const dir = scanResult?.serviceDir && scanResult.serviceDir !== 'root' ? scanResult.serviceDir : null;
  const lines = [
    'build:',
    '  stage: build',
    '  image: node:20-alpine',
    '  script:',
  ];
  if (dir) lines.push(`    - cd ${dir}`);
  lines.push('    - npm ci', '    - npm run build || true');
  lines.push('  artifacts:');
  lines.push('    paths:');
  lines.push(dir ? `      - ${dir}/node_modules/` : '      - node_modules/');
  return lines.join('\n');
}

function buildJobPython(scanResult) {
  const dir = scanResult?.serviceDir && scanResult.serviceDir !== 'root' ? scanResult.serviceDir : null;
  return [
    'build:',
    '  stage: build',
    '  image: python:3.11-slim',
    dir ? `  variables:\n    WORKING_DIR: ${dir}` : '',
    '  script:',
    dir ? `    - cd ${dir}` : '',
    '    - pip install -r requirements.txt || pip install .',
    '  artifacts:',
    '    paths:',
    '      - .venv/',
  ].filter(Boolean).join('\n');
}

function buildJobGeneric() {
  return [
    'build:',
    '  stage: build',
    '  image: alpine:latest',
    '  script:',
    '    - echo "No language detected; add build steps for your stack."',
  ].join('\n');
}

function testJobNode(scanResult) {
  const dir = scanResult?.serviceDir && scanResult.serviceDir !== 'root' ? scanResult.serviceDir : null;
  return [
    'test:',
    '  stage: test',
    '  image: node:20-alpine',
    '  dependencies:',
    '    - build',
    dir ? `  variables:\n    WORKING_DIR: ${dir}` : '',
    '  script:',
    dir ? `    - cd ${dir}` : '',
    '    - npm ci',
    '    - npm test || npm run test || echo "No test script defined"',
  ].filter(Boolean).join('\n');
}

function testJobPython(scanResult) {
  const dir = scanResult?.serviceDir && scanResult.serviceDir !== 'root' ? scanResult.serviceDir : null;
  return [
    'test:',
    '  stage: test',
    '  image: python:3.11-slim',
    '  dependencies:',
    '    - build',
    '  script:',
    dir ? `    - cd ${dir}` : '',
    '    - pip install -r requirements.txt || pip install .',
    '    - pytest || python -m pytest || echo "No tests found"',
  ].filter(Boolean).join('\n');
}

function testJobGeneric() {
  return [
    'test:',
    '  stage: test',
    '  script:',
    '    - echo "Add test steps for your stack."',
  ].join('\n');
}

function deployJobCloudRun(scanResult, gcpPlan, deploymentConfig) {
  const cloudRun = deploymentConfig.cloudRun || {};
  const serviceName = cloudRun.serviceName || 'app';
  const region = cloudRun.region || deploymentConfig.region || 'us-central1';
  // Use Cloud Build so we don't need Docker on the runner
  const imageRef = `gcr.io/${'$'}GCP_PROJECT_ID/${serviceName}:${'$'}CI_COMMIT_SHA`;

  return [
    'deploy:',
    '  stage: deploy',
    '  image:',
    '    name: google/cloud-sdk:alpine',
    '    entrypoint: [""]',
    '  dependencies: []',
    '  script:',
    '    - echo "$GCP_SERVICE_ACCOUNT_KEY" | base64 -d > key.json',
    '    - gcloud auth activate-service-account --key-file=key.json',
    '    - gcloud config set project $GCP_PROJECT_ID',
    `    - gcloud builds submit --tag ${imageRef} . --async`,
    `    - gcloud run deploy ${serviceName} --image=${imageRef} --region=${region} --platform=managed --allow-unauthenticated`,
    '  only:',
    '    - main',
    '    - master',
  ].join('\n');
}

function deployJobPlaceholder() {
  return [
    'deploy:',
    '  stage: deploy',
    '  script:',
    '    - echo "Add deploy steps (e.g. Cloud Run, Cloud Build, or your CD target)."',
    '  only:',
    '    - main',
    '    - master',
  ].join('\n');
}

module.exports = { generatePipelineYaml };
